export const tech = {
  react: 'https://pt-br.reactjs.org/',
  hooks: 'https://pt-br.reactjs.org/docs/hooks-intro.html',
  redux: 'https://redux.js.org/',
  'redux-saga': 'https://redux-saga.js.org/',
  'react-router-dom': 'https://reactrouter.com/web/guides/quick-start',
  'react-icons': 'http://react-icons.github.io/react-icons',
  jest: 'https://jestjs.io/',
  storybook: 'https://storybook.js.org/',
  'styled-components': 'https://styled-components.com/',
  prettier: 'https://prettier.io/',
  eslint: 'https://eslint.org/',
  webpack: 'https://webpack.js.org/',
  babel: 'https://babeljs.io/',
  axios: 'https://github.com/axios/axios',
  polished: 'https://polished.js.org/',
  dotenv: 'https://www.npmjs.com/package/dotenv',
  docker: 'https://www.docker.com/',
  'docker-compose': 'https://docs.docker.com/compose/',
};
