version: '3.8'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - '/app/node_modules'
      - './:/app'
  storybook:
    build: .
    command: yarn storybook
    ports:
      - '6006:6006'

